package com.hogglepot;

public class Story {
	private String storyID;
	private String storyTitle;
	private String storyDate;
	private String storyContent;
	private String authorID;
	
	// ************* Constructors ************ \\
	// No argument constructor
	public Story() {
		super();
	}

	// This constructor used to get the entire story.
	public Story(String storyID, String storyTitle, String storyDate, String storyContent,
			String authorID) {
		super();
		this.storyID = storyID;
		
	}
	
	// This constructor used to get a story listing.
	public Story(String storyID, String storyTitle, String storyDate) {
		super();
		this.storyID = storyID;
		this.storyTitle = storyTitle;
		this.storyDate = storyDate;
		
	}
	
	// Constructor for adding a story. The ID is generated by DB.
	public Story(String storyTitle, String storyDate, String storyContent, String authorID) {
		super();
		this.storyTitle = storyTitle;
		this.storyDate = storyDate;
		this.storyContent = storyContent;
		this.authorID = authorID;
	}
	
	// ************* Getter & Setters ************** \\
	public String getStoryID() {
		return storyID;
	}

	public void setStoryID(String storyID) {
		this.storyID = storyID;
	}

	public String getStoryTitle() {
		return storyTitle;
	}

	public void setStoryTitle(String storyTitle) {
		this.storyTitle = storyTitle;
	}

	public String getStoryDate() {
		return storyDate;
	}

	public void setStoryDate(String storyDate) {
		this.storyDate = storyDate;
	}

	public String getStoryContent() {
		return storyContent;
	}

	public void setStoryContent(String storyContent) {
		this.storyContent = storyContent;
	}

	public String getAuthorID() {
		return authorID;
	}

	public void setAuthorID(String authorID) {
		this.authorID = authorID;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Story other = (Story) obj;
		if (authorID != other.authorID)
			return false;
		if (storyContent == null) {
			if (other.storyContent != null)
				return false;
		} else if (!storyContent.equals(other.storyContent))
			return false;
		if (storyDate == null) {
			if (other.storyDate != null)
				return false;
		} else if (!storyDate.equals(other.storyDate))
			return false;
		if (storyID != other.storyID)
			return false;
		if (storyTitle == null) {
			if (other.storyTitle != null)
				return false;
		} else if (!storyTitle.equals(other.storyTitle))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Story [storyID=" + storyID + ", storyTitle=" + storyTitle
				+ ", storyDate=" + storyDate + ", storyContent=" + storyContent
				+ ", authorID=" + authorID + "]";
	}
	
	
}
